name: Validate Renovate Config
on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Validate Renovate config
        run: npx --yes --package renovate -- renovate-config-validator --strict default.json
